"""
Order ORM model + OrderItem ORM model.

Order
-----
- order_number is workspace-scoped unique (generated by the application layer).
- table_id and area_id are nullable (takeaway / delivery orders have no table).
- item_id on OrderItem is intentionally NOT a foreign key so that deleted items
  do not cascade-delete historical order lines.
- customer_id is nullable; set when the order is placed by a known Customer
  (identified by mobile number). Walk-in orders without a mobile number leave
  this NULL.

status values        : pending | confirmed | preparing | ready | delivered | cancelled
payment_status values: unpaid | paid | refunded | partial
order_type values    : dine_in | takeaway | delivery
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from src.models.Base import Base, EntityMixin, UUIDPrimaryKeyMixin


# --------------------------------------------------------------------------- #
# Order                                                                        #
# --------------------------------------------------------------------------- #
class Order(UUIDPrimaryKeyMixin, EntityMixin, Base):
    """A customer order."""

    __tablename__ = "orders"

    order_number: Mapped[str] = mapped_column(String(50), nullable=False)
    order_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="dine_in",
        server_default="dine_in",
        comment="dine_in | takeaway | delivery",
    )
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="pending",
        server_default="pending",
        comment="pending | confirmed | preparing | ready | delivered | cancelled",
    )
    payment_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="unpaid",
        server_default="unpaid",
        comment="unpaid | paid | refunded | partial",
    )
    payment_method: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)

    # ------------------------------------------------------------------ #
    # Customer info (denormalised snapshot)                               #
    # ------------------------------------------------------------------ #
    customer_name: Mapped[str] = mapped_column(String(200), nullable=False)
    customer_email: Mapped[Optional[str]] = mapped_column(String(254), nullable=True)
    customer_phone: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)

    # ------------------------------------------------------------------ #
    # Financials                                                           #
    # ------------------------------------------------------------------ #
    subtotal: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0, server_default="0")
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0, server_default="0")
    service_charge: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0, server_default="0")
    discount_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0, server_default="0")
    total_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False, default=0, server_default="0")
    currency: Mapped[str] = mapped_column(String(10), nullable=False, default="USD", server_default="USD")

    # ------------------------------------------------------------------ #
    # Misc                                                                 #
    # ------------------------------------------------------------------ #
    special_instructions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    order_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # ------------------------------------------------------------------ #
    # Foreign keys                                                         #
    # ------------------------------------------------------------------ #
    workspace_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("workspaces.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    persona_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("personas.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    # Nullable: takeaway / delivery orders have no table
    table_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("tables.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    area_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("areas.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    # Nullable: set when the order is linked to a known Customer record
    customer_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("customers.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Relationships                                                        #
    # ------------------------------------------------------------------ #
    persona: Mapped["Persona"] = relationship(  # noqa: F821
        "Persona",
        back_populates="orders",
        lazy="select",
    )
    table: Mapped[Optional["Table"]] = relationship(  # noqa: F821
        "Table",
        back_populates="orders",
        lazy="select",
    )
    area: Mapped[Optional["Area"]] = relationship(  # noqa: F821
        "Area",
        back_populates="orders",
        lazy="select",
    )
    customer: Mapped[Optional["Customer"]] = relationship(  # noqa: F821
        "Customer",
        back_populates="orders",
        lazy="select",
    )
    items: Mapped[list["OrderItem"]] = relationship(
        "OrderItem",
        back_populates="order",
        cascade="all, delete-orphan",
        passive_deletes=True,
        lazy="select",
    )

    # ------------------------------------------------------------------ #
    # Indexes & constraints                                                #
    # ------------------------------------------------------------------ #
    __table_args__ = (
        UniqueConstraint("order_number", "workspace_id", name="uq_orders_order_number_workspace"),
        Index("ix_orders_status", "status"),
        Index("ix_orders_payment_status", "payment_status"),
        Index("ix_orders_is_active", "is_active"),
        Index("ix_orders_order_date", "order_date"),
    )

    def __repr__(self) -> str:
        return f"<Order id={self.id} number={self.order_number!r} status={self.status!r}>"


# --------------------------------------------------------------------------- #
# OrderItem                                                                    #
# --------------------------------------------------------------------------- #
class OrderItem(UUIDPrimaryKeyMixin, EntityMixin, Base):
    """
    A single line item within an Order.

    item_id is stored as a plain BigInteger column (NOT a FK) so that soft-deleted
    or hard-deleted items do not break historical order records.
    item_name is denormalised for the same reason.
    """

    __tablename__ = "order_items"

    # Intentionally NOT a FK — item may be deleted after order is placed
    item_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    item_name: Mapped[str] = mapped_column(String(200), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    total_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)

    # ------------------------------------------------------------------ #
    # Foreign keys                                                         #
    # ------------------------------------------------------------------ #
    order_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Relationships                                                        #
    # ------------------------------------------------------------------ #
    order: Mapped["Order"] = relationship(
        "Order",
        back_populates="items",
        lazy="select",
    )

    # ------------------------------------------------------------------ #
    # Indexes                                                              #
    # ------------------------------------------------------------------ #
    __table_args__ = (
        Index("ix_order_items_item_id", "item_id"),
        Index("ix_order_items_is_active", "is_active"),
    )

    def __repr__(self) -> str:
        return f"<OrderItem id={self.id} order_id={self.order_id} item={self.item_name!r} qty={self.quantity}>"
